### ISSUE TITLE
Cool distro, may I include it in CustomPiOS List of Distributions?

### ISSUE THREAD

**Issue by guysoft** [raymondh2/MainsailOS#15]
Hey,
Would love to add it to this section in the readme:
https://github.com/guysoft/CustomPiOS#list-of-distributions-using-custompios

If you like you can also PR it yourself.

**Comment by raymondh2** [comment]
Sorry about the delay. I'm glad you think it is a neat distro! Please go ahead and list it. Thank you for all of your work on CustomPiOS and OctoPi!
