### ISSUE TITLE
Worth considering making MainsailOS (mostly) RO ?

### ISSUE THREAD

**Issue by al3ph** [raymondh2/MainsailOS#19]
Not sure if this has been considered, but due to our printers likely being on for long periods of time, this might be worth considering.

Might be tricky to implement as parts of the system will need to be RW (config/virtual_sdcard/thumbnail dir).
I would guess the Pi homespace needs to be RW, but most other things can be RO, or tmpfs.

[make-your-raspberry-pi-file-system-read-only](https://medium.com/swlh/make-your-raspberry-pi-file-system-read-only-raspbian-buster-c558694de79)

**Comment by raymondh2** [comment]
For the time being no. This adds will need additional implementation from Moonraker in order to update parts that are in read only areas. Also this will add to confusion of people who are used to the whole Pi file system being read-write.
