### ISSUE TITLE
[Solved] Moonraker doesn't start when pulling the latest update from git

### ISSUE THREAD

**Issue by dormunis** [raymondh2/MainsailOS#27]
When installing a fresh MainsailOS 0.3, everything is nice an installed.

I went into klipper and moonraker and pulled the latest changes and when I tried accessing the web ui, it couldn't connect.
After quickly debugging the issue, what needs to be done about it is installing 2 packages using the moonraker-env:

`~/moonraker-env/bin/pip install streaming-form-data lmdb`

I just thought you might wanna know (I'm sorry I didn't create a PR myself, I needed to address other things and didn't want to get into what installs what in this repo, but I wrote this issue to potentially save you or anybody else any trouble debugging in the future)

**Comment by raymondh2** [comment]
This is not a MainsailOS issue. This is a procedure issue
