### ISSUE TITLE
fyi, had to add client_max_body_size 100M; to nginx.conf

### ISSUE THREAD

**Issue by sanderboer** [raymondh2/MainsailOS#31]
Hi,

leaving this as a remark, I installed mainsail via kiauh on my octopi install. I was up and running fairly quickly, but uploading gcode failed continuously, despite a correct setup in printer.cfg.
Found the error in the nginx log and had to add "client_max_body_size 100M;" to the http{} section in nginx.conf.

**Comment by raymondh2** [comment]
Resolved.
