### ISSUE TITLE
[FR] install deps, config for resonance measurement

### ISSUE THREAD

**Issue by blalor** [raymondh2/MainsailOS#45]
(I'm blindly copying this from https://github.com/meteyou/mainsail/issues/297, where I placed the issue incorrectly earlier…) 

**Is your feature request related to a problem? Please describe.**

When following the guide to performance [resonance measurements](https://www.klipper3d.org/Measuring_Resonances.html) I was surprised that SPI was not enabled, and that numpy and matplotlib were not already installed.

**Describe the solution you'd like**

Preinstall the dependencies and enable SPI.

**Describe alternatives you've considered**

Installing them manually on the system is certainly doable, but numpy in particular is a big dependency and slow to build.

**Additional context**

<img width="718" alt="image" src="https://user-images.githubusercontent.com/109915/122684832-e418c580-d1d5-11eb-9c25-8219fcdfa612.png">

I suspect that installing `python-numpy` before creating the virtualenv will make for much faster installation, although the venv may need the flag for including site packages.

**Comment by raymondh2** [comment]
I have played with doing this before. However due to the fact we use QEMU to build the image this takes too long and times out the github action.
