### ISSUE TITLE
Not working on Arduino mega and RAMPS 1.4

### ISSUE THREAD

**Issue by bojfik** [raymondh2/MainsailOS#6]
It's not working with RAMPS 1.4 
If you do a firmware update on ArduinoMega, in my case with RAMPS 1.4 it won't work. After copying the printer.cfg, it turns out that there are incorrect readings on the housing of the temperature sensors, i.e. on the hotend and the bed, and there is a wrong pin map. Check it out
I'm going back to Octopi

**Comment by raymondh2** [comment]
This sounds like a Klipper bug or change see the config changes on the Klipper repo https://github.com/KevinOConnor/klipper/blob/master/docs/Config_Changes.md
